version: '3'

services:
  app:
    build: .
    container_name: app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
