# Generated by Django 5.2.4 on 2025-07-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("smart_student", "0002_alter_userinformation_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinformation",
            name="chat_history",
            field=models.TextField(blank=True, null=True),
        ),
    ]
