# Generated by Django 5.2.4 on 2025-07-14 07:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("smart_student", "0003_userinformation_chat_history"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userinformation",
            name="chat_history",
        ),
    ]
