# Generated by Django 5.2.4 on 2025-07-14 07:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("smart_student", "0004_remove_userinformation_chat_history"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinformation",
            name="Email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="userinformation",
            name="User_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
